name: Build and Release

on:
  workflow_call:
    secrets:
      KEYSTORE_FILE:
        required: true
      KEYSTORE_PASSWORD:
        required: true
      KEY_PASSWORD:
        required: true
      KEY_ALIAS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up environment
      run: |
        echo "storeFilePath=$(pwd)/keystore.jks" > signing.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> signing.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> signing.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> signing.properties
        echo -n "${{ secrets.KEYSTORE_FILE }}" | base64 --decode --ignore-garbage > keystore.jks

    - name: Build
      run: |
        ./gradlew clean
        ./gradlew assembleRelease --no-daemon

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.run_id }}
        path: app/build/outputs/apk/release/*.apk
        if-no-files-found: error
        overwrite: true
        retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - name: download
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.run_id }}
        path: artifacts/
    - run: ls -R artifacts
    - name: Upload APKs to release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          artifacts/*.apk

